# Generated by Django 5.2.7 on 2026-04-15 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('married', models.CharField(choices=[('Yes', 'Так'), ('No', 'Ні')], max_length=3)),
                ('dependents', models.CharField(max_length=5)),
                ('education', models.CharField(max_length=20)),
                ('self_employed', models.CharField(max_length=3)),
                ('property_area', models.CharField(max_length=20)),
                ('applicant_income', models.FloatField()),
                ('coapplicant_income', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('loan_amount_term', models.FloatField()),
                ('credit_history', models.FloatField()),
                ('probability', models.FloatField(help_text='Ймовірність схвалення у відсотках')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запиту')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
